baseurl = "/"
title = "Koderhtml's blog"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "KCoderhtml's Blog"
    description = "My Blog: where I write about things!"
    github = "https://github.com/kcoderhtml"
    twitter = "https://twitter.com/XXX"
    email = "XXX@example.com"
    opengraph = true
    shareTwitter = false
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
