baseurl = "/"
title = "Koderhtml's blog"
theme = "ghostwriter"
copyright = "Kieran Klukas"
googleAnalytics = "G-WQEG4L6932"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "KCoderhtml's Blog"
    description = "My Blog: where I write about things!"
    github = "https://github.com/kcoderhtml"
    email = "XXX@example.com"
    opengraph = true
    shareTwitter = false
    dateFormat = "Mon, Jan 2, 2006"
    rss = true
    readingTime = true
    readingTimeText = "Estimated reading time:"

[Permalinks]
    post = "/:filename/"
